package com.map711s.namibiahockey

/**
 * BuildConfig contains build-specific configuration constants.
 * This class is typically auto-generated by the Android Gradle Plugin,
 * but this manual version can be used for testing or specific customization.
 */
object BuildConfig {
    // Application ID from your build.gradle.kts
    const val APPLICATION_ID = "com.map711s.namibiahockey"

    // Build type - can be "debug" or "release"
    const val BUILD_TYPE = "debug"

    // Version information from your build.gradle.kts
    const val VERSION_CODE = 1
    const val VERSION_NAME = "1.0"

    // Debug flag - true when building debug variant
    const val DEBUG = true

    // Base URL for your API connections (if applicable)
    const val API_BASE_URL = "https://namibiahockey.org/api/"

    // Firebase configuration
    const val FIREBASE_PROJECT_ID = "namibiahockey"

    // Hockey-specific configuration constants
    const val PRIVACY_POLICY_URL = "https://namibiahockey.org/privacy"
    const val TERMS_URL = "https://namibiahockey.org/terms"
    const val SUPPORT_EMAIL = "support@namibiahockey.org"

    // Feature toggles (for feature flags)
    const val ENABLE_CHAT_FEATURE = false
    const val ENABLE_LIVE_SCORING = true

    // Time constants
    const val DEFAULT_TIMEOUT_MS = 30000L // 30 seconds

    // Cache configuration
    const val CACHE_SIZE_MB = 50
    const val CACHE_EXPIRY_DAYS = 7
}